BugTracker/Models/Domain/TicketAttachment.cs
using System;

namespace BugTracker.Models.Domain
{
    public class TicketAttachment
    {
        public Guid Id { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string FileUrl { get; set; }
        public DateTime DateCreated { get; set; }

        public virtual Ticket Ticket { get; set; }
        public Guid TicketId { get; set; }

        public virtual ApplicationUser User { get; set; }
        public string UserId { get; set; }


        public TicketAttachment()
        {
            Id = Guid.NewGuid();
            DateCreated = DateTime.Now;
        }

        public override string ToString() => $"Ticket Attachment - Description: {Description}";
    }
}

BugTracker/Models/Domain/TicketAttachments.cs
using System;

namespace BugTracker.Models.Domain
{
    public class TicketAttachments
    {
        public Guid Id { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string FileUrl { get; set; }
        public DateTime DateCreated { get; set; }

        public virtual Ticket Ticket { get; set; }
        public Guid TicketId { get; set; }

        public virtual ApplicationUser User { get; set; }
        public string UserId { get; set; }


        public TicketAttachments()
        {
            Id = Guid.NewGuid();
            DateCreated = DateTime.Now;
        }

        public override string ToString() => $"Ticket Attachment - Description: {Description}";
    }
}

BugTracker/Models/ViewModels/Project/CreateViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BugTracker.Models.ViewModels.Project
{
    public class CreateViewModel
    {
        public List<HelperUserViewModel> Users { get; set; }

        [Required]
        public string Name { get; set; }

        public List<SelectListItem> UsersAddList { get; set; }

        [Display(Name = "Assign Users")]
        public string[] SelectedUsersToAdd { get; set; }
    }
}

BugTracker/Models/ViewModels/TicketAttachment/TicketAttachmentCreateViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace BugTracker.Models.ViewModels.TicketAttachment
{
    public class TicketAttachmentCreateViewModel
    {
        [Required]
        [StringLength(250, MinimumLength = 5)]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase Media { get; set; }

        public Guid TicketId { get; set; }
        public string TicketTitle { get; set; }

        public static TicketAttachmentCreateViewModel CreateNewViewModel(Domain.Ticket ticket)
        {
            if (ticket == null)
            {
                throw new ArgumentNullException(nameof(ticket));
            }
            
            return new TicketAttachmentCreateViewModel()
            {
                TicketId = ticket.Id,
                TicketTitle = ticket.Title,
            };
        }
    }
}

BugTracker/Models/ViewModels/TicketAttachment/TicketAttachmentDeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;

namespace BugTracker.Models.ViewModels.TicketAttachment
{
    public class TicketAttachmentDeleteViewModel
    {
        public Guid Id { get; set; }
        [Display(Name = "File Name")]
        public string FileName { get; set; }
        public string Description { get; set; }
        public Guid TicketId { get; set; }
        public string TicketName { get; set; }

        public static TicketAttachmentDeleteViewModel CreateNewViewModel(Domain.TicketAttachment ticketAttachment)
        {
            if (ticketAttachment == null)
            {
                throw new ArgumentNullException(nameof(ticketAttachment));
            }

            return new TicketAttachmentDeleteViewModel()
            {
                Id = ticketAttachment.Id,
                FileName = Path.GetFileName(ticketAttachment.FilePath),
                Description = ticketAttachment.Description,
                TicketId = ticketAttachment?.Ticket.Id ?? throw new ArgumentException("TicketAttachment wasn't attached to ticket"),
                TicketName = ticketAttachment?.Ticket.Title ?? throw new ArgumentException("TicketAttachment wasn't attached to ticket"),
            };
        }
    }
}

BugTracker/Models/ViewModels/TicketAttachment/TicketAttachmentIndexViewModel.cs
using System;
using System.IO;
using TicketIndexViewModel = BugTracker.Models.ViewModels.Ticket.TicketIndexViewModel;

namespace BugTracker.Models.ViewModels.TicketAttachment
{
    public class TicketAttachmentIndexViewModel
    {
        public Guid Id { get; set; }
        public string Description { get; set; }
        public string FileUrl { get; set; }
        public string FilePath { get; set; }
        public string FileName {get;set;}
        public DateTime DateCreated { get; set; }

        public TicketIndexViewModel Ticket { get; set; }
        public Guid TicketId { get; set; }

        public HelperUserViewModel User { get; set; }
        public string UserId { get; set; }

        public static TicketAttachmentIndexViewModel CreateNewViewModel(string currentUserId, Domain.TicketAttachment ticketAttachment, ApplicationDbContext dbContext)
        {
            if (ticketAttachment == null)
            {
                throw new ArgumentNullException(nameof(ticketAttachment));
            }

            TicketIndexViewModel ticket = TicketIndexViewModel.CreateNewViewModel(currentUserId, ticketAttachment.Ticket) ?? throw new ArgumentException();
            HelperUserViewModel user = HelperUserViewModel.CreateNewViewModel(ticketAttachment.User, dbContext) ?? throw new ArgumentException();
            
            return new TicketAttachmentIndexViewModel()
            {
                Id = ticketAttachment.Id,
                Description = ticketAttachment.Description,
                FilePath = ticketAttachment.FilePath,
                FileUrl = ticketAttachment.FileUrl,
                DateCreated = ticketAttachment.DateCreated,
                FileName = Path.GetFileName(ticketAttachment.FilePath),
                User = user,
                UserId = user.Id,

                Ticket = ticket,
                TicketId = ticket.Id,
            };
        }
    }
}

BugTracker/Controllers/TicketAttachmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BugTracker.Models;
using BugTracker.Models.Domain;
using BugTracker.Models.ViewModels.TicketAttachment;
using BugTracker.MyHelpers.DB_Repositories;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    public class TicketAttachmentController : Controller
    {
        private readonly ApplicationDbContext DbContext;
        private readonly TicketRepository TicketRepository;
        private readonly UserRepository UserRepository;
        private readonly TicketAttachmentRepository TicketAttachmentRepository;

        public TicketAttachmentController()
        {
            DbContext = new ApplicationDbContext();
            TicketRepository = new TicketRepository(DbContext);
            UserRepository = new UserRepository(DbContext);
            TicketAttachmentRepository = new TicketAttachmentRepository(DbContext);
        }

        // GET: TicketAttachment
        public ActionResult Index(Guid? ticketId)
        {
            if (!ticketId.HasValue)
            {
                return RedirectToAction(nameof(TicketController.Index), "Ticket");
            }
            else if (TicketRepository.DoesTicketExist(ticketId.Value))
            {
                return RedirectToAction(nameof(TicketController.Details), "Ticket", new { id = ticketId });
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }

        // GET: TicketAttachment/Create
        public ActionResult Create(Guid? ticketId)
        {
            if (!ticketId.HasValue || !TicketRepository.DoesTicketExist(ticketId.Value))
            {
                return RedirectToAction(nameof(Index));
            }
            Ticket foundTicket = TicketRepository.GetTicket(ticketId.Value) ?? throw new Exception("This shouldn't happen");
            string userId = User.Identity.GetUserId();
            if (TicketRepository.CanUserEditTicket(userId, foundTicket.Id))
            {
                return View(TicketAttachmentCreateViewModel.CreateNewViewModel(foundTicket));
            }
            else
            {
                return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"You don't have the appropriate permissions to add a attachment to this ticket ({foundTicket.Title})" });
            }
        }

        // POST: TicketAttachment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TicketAttachmentCreateViewModel formData)
        {
            if (formData == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                string userId = User.Identity.GetUserId();
                if (!UserRepository.DoesUserExist(userId))
                {
                    throw new Exception("User Not Found");
                }
                if (!TicketRepository.CanUserEditTicket(userId, formData.TicketId))
                {
                    return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"You don't have the appropriate permissions to add a attachment to this ticket ({formData.TicketTitle})" });
                }
                if (formData.Media == null)
                {
                    ModelState.AddModelError(nameof(TicketAttachmentCreateViewModel.Media), "You must attach/upload a file");
                    return View(formData);
                }

                FileSystemRepository fileSystemRepository = new FileSystemRepository(Server, new HashSet<string>());

                TicketAttachment newTicketAttachment = new TicketAttachment()
                {
                    Description = formData.Description,
                    UserId = userId,
                    TicketId = formData.TicketId,
                };

                (bool hasSuccessfullySaved, string filePath, string fileUrl, string resultMessage) = fileSystemRepository.SaveFile(formData.Media);

                if (!hasSuccessfullySaved)
                {
                    throw new Exception($"File wasn't saved\n\tFileSystemRepository - Message: {resultMessage}");
                }

                newTicketAttachment.FilePath = filePath;
                newTicketAttachment.FileUrl = Url.Content(fileUrl);

                DbContext.TicketAttachments.Add(newTicketAttachment);
                int savedEntities = DbContext.SaveChanges();

                if (savedEntities <= 0)
                {
                    throw new Exception($"Database wasn't saved\n\tFileSystemRepository - Message: {resultMessage}");
                }

                #region Send Emails
                List<TicketNotification> ticketNotifications = new TicketNotificationRepository(DbContext)
                    .GetTicketsTicketNotifications(formData.TicketId)
                    .ToList();

                if (ticketNotifications.Count > 0)
                {
                    ApplicationUser foundAttachmentAuthor = UserRepository.GetUserById(userId) ?? throw new Exception("Attachment author not found");

                    string callBackUrl = Url.Action(nameof(TicketController.Details), "Ticket", new { id = formData.TicketId }, Request.Url.Scheme);
                    
                    EmailSystemRepository emailRepository = new EmailSystemRepository();
                    string body = emailRepository.GetSampleBodyString(
                        $"The new attachment was added to the <i>\"{formData.TicketTitle}\"</i> ticket",
                        $"made by {foundAttachmentAuthor.Email}",
                        $"Click here for the ticket details",
                        $"{callBackUrl}");

                    emailRepository.SendAll(("A new attachment was added", body), ticketNotifications);
                }
                #endregion

                return RedirectToAction(nameof(Index), new { ticketId = formData.TicketId });
            }
            catch
            {
                if (formData?.TicketId != null && !TicketRepository.DoesTicketExist(formData.TicketId))
                {
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Create), new { ticketId = formData.TicketId });
            }
        }

        // GET: TicketAttachment/Delete/{id}
        public ActionResult Delete(Guid? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(Index));
            }
            string userId = User.Identity.GetUserId();
            TicketAttachment foundTicketAttachment = TicketAttachmentRepository.GetTicketAttachment(id.Value);
            if (foundTicketAttachment == null)
            {
                return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"Ticket Attachment wasn't deleted (Not Found)" });
            }
            else if (!TicketRepository.CanUserEditTicket(userId, foundTicketAttachment.TicketId))
            {
                return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"You don't have the appropriate permissions to add a attachment to this ticket ({foundTicketAttachment.Ticket.Title})" });
            }
            return View(TicketAttachmentDeleteViewModel.CreateNewViewModel(foundTicketAttachment));
        }

        // POST: TicketAttachment/Delete/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid? id, TicketAttachmentDeleteViewModel formData)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                string userId = User.Identity.GetUserId();
                TicketAttachment foundTicketAttachment = TicketAttachmentRepository.GetTicketAttachment(formData.Id);
                if (foundTicketAttachment == null)
                {
                    return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"Ticket Attachment wasn't deleted (Not Found)" });
                }
                else if (!TicketRepository.CanUserEditTicket(userId, foundTicketAttachment.TicketId))
                {
                    return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"You don't have the appropriate permissions to add a attachment to this ticket ({foundTicketAttachment.Ticket.Title})" });
                }
                DbContext.TicketAttachments.Remove(foundTicketAttachment);
                int numberOfSavedEntities = DbContext.SaveChanges();
                if (numberOfSavedEntities <= 0)
                {
                    return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = $"Ticket Attachment wasn't deleted (Database Error)" });
                }
                return RedirectToAction(nameof(Index), new { ticketId = formData.TicketId });
            }
            catch
            {
                return RedirectToAction(nameof(Delete), new { id = formData.Id });
            }
        }

    }
}

BugTracker/Views/TicketAttachment/Create.cshtml
@model TicketAttachmentCreateViewModel

@{
    ViewBag.Title = "Add new Attachment";
    bool isAdminOrProjectManager = User.IsInRole(nameof(UserRolesEnum.Admin)) || User.IsInRole(nameof(UserRolesEnum.ProjectManager));
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        const fileInput = document.querySelector(".custom-file-input");
        const fileButton = document.querySelector(".custom-file-upload");
        const btnMsg = fileButton.textContent;
        fileInput.addEventListener("change", (e) => {
            const fileName = document.querySelector(".custom-file-input").files[0].name;
            fileButton.lastElementChild.textContent = `${btnMsg} - ${fileName}`;
        });

        setTimeout(() => {
            document.querySelector("div.tox-tinymce").setAttribute("style", "height: 300px;");
        }, 500);
    </script>
}

@section Styles
{
    <style>
        input[type="file"] {
            display: none;
        }

        .validation-summary-errors ul {
            margin-left: 50px;
        }
    </style>
}

<div class="col-lg-7">
    <div class="card">
        <div class="header">
            <h4 class="title">
                @* TITLE HERE *@
                @ViewBag.Title
            </h4>
            <p class="category">
                @* SUBTITLE HERE *@
                for "@Model.TicketTitle" ticket
            </p>
        </div>
        <div class="content">
            @* CONTENT HERE *@
            @using (Html.BeginForm(nameof(TicketAttachmentController.Create), "TicketAttachment", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.TicketId)
                @Html.HiddenFor(model => model.TicketTitle)

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control", style = "min-width: 80%;" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Media, htmlAttributes: new { @class = "form-check-label text-bold control-label col-md-2" })
                        <div class="col-md-10">
                            <label for="upload" class="custom-file-upload btn btn-default">
                                <input id="upload" class="custom-file-input" type="file" name="@(nameof(Model.Media))" />
                                <span>Upload A File</span>
                            </label>
                            @Html.ValidationMessageFor(model => model.Media, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add Attachment" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }

            @* FOOTER HERE *@
            <div class="footer">
                <hr />
                <div class="stats">
                    <i style="font-size: 150%; font-weight: 600; position: relative; top: 3.5px;" class="pe-7s-back"></i>
                    <span class="text-danger">Discard Attachment</span> and Go To
                    [
                    <span>
                        @Html.ActionLink($"{Model.TicketTitle} (Ticket Details)", nameof(TicketCommentController.Index), new { ticketId = Model.TicketId }, new { @class = "text-warning" })
                    </span>
                    ]
                </div>
            </div>
        </div>
    </div>
</div>

BugTracker/Views/TicketAttachment/Delete.cshtml
@model TicketAttachmentDeleteViewModel

@{
    ViewBag.Title = "Delete Ticket Attachment";
}

<div class="col-lg-6">
    <div class="card">
        <div class="header">
            <h4 class="title">
                @* TITLE HERE *@
                Are you sure you want to delete this attachment
            </h4>
            <p class="category">
                @* SUBTITLE HERE *@
                from "@Html.DisplayFor(model => model.TicketName)" ticket
            </p>
        </div>
        <div class="content">
            @* CONTENT HERE *@
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.FileName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.FileName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description):
                </dt>
                <dd style="overflow-wrap: break-word;">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>


            @* FOOTER HERE *@
            <div class="footer">
                <hr />
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.TicketId)
                    <div class="stats">
                        <div class="form-actions no-color">
                            @Html.ActionLink("Do Not Delete", nameof(TicketCommentController.Index), new { ticketId = Model.TicketId }, new { @class = "btn btn-primary", style = "" })
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>