BugTracker/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BugTracker.Models;
using BugTracker.Models.Domain;
using BugTracker.Models.Filters.Actions;
using BugTracker.Models.Filters.Authorize;
using BugTracker.Models.ViewModels.Ticket;
using BugTracker.MyHelpers;
using BugTracker.MyHelpers.DB_Repositories;
using Microsoft.AspNet.Identity;

namespace BugTracker.Controllers
{
    public class TicketController : Controller
    {
        private readonly ApplicationDbContext DbContext;
        private readonly TicketRepository TicketRepository;
        private readonly UserRoleRepository UserRoleRepository;
        private readonly UserRepository UserRepository;
        private readonly ProjectRepository ProjectRepository;
        private readonly TicketNotificationRepository TicketNotificationRepository;

        public TicketController()
        {
            DbContext = new ApplicationDbContext();
            TicketRepository = new TicketRepository(DbContext);
            UserRepository = new UserRepository(DbContext);
            UserRoleRepository = new UserRoleRepository(DbContext);
            ProjectRepository = new ProjectRepository(DbContext);
            TicketNotificationRepository = new TicketNotificationRepository(DbContext);
        }

        // GET: Ticket
        [Route("Ticket/{whatTickets?}")]
        public ActionResult Index(string whatTickets = "", string error = "")
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser currentUser = UserRepository.GetUserById(userId);
            if (!string.IsNullOrWhiteSpace(error))
            {
                ModelState.AddModelError("", error);
            }

            if (currentUser == null)
            {
                return RedirectToAction(nameof(HomeController.Index), new { controller = "Home" });
            }

            List<TicketIndexViewModel> model;

            if (!string.IsNullOrWhiteSpace(whatTickets))
            {
                const string assigned = "Assigned";
                const string created = "Created";
                if (whatTickets.ToLower() == assigned.ToLower())
                {
                    ViewBag.whatTickets = assigned;
                    model = TicketRepository.GetUserAssignedTickets(userId)
                        .ToList()
                        //.Where(ticket => TicketRepository.CanUserViewTicket(userId, ticket.Id)) // shouldn't need to check, if the user is assigned to the ticket
                        .Select(ticket => TicketIndexViewModel.CreateNewViewModel(userId, ticket))
                        .ToList();
                }
                else if (whatTickets.ToLower() == created.ToLower())
                {
                    ViewBag.whatTickets = created;
                    model = TicketRepository.GetUserCreatedTickets(userId)
                    .ToList()
                    //.Where(ticket => TicketRepository.CanUserViewTicket(userId, ticket.Id)) // shouldn't need to check, if the user created the ticket
                    .Select(ticket => TicketIndexViewModel.CreateNewViewModel(userId, ticket))
                    .ToList();
                }
                else //if (whatTickets.ToLower() == "all") // defaults to this else block { ... }
                {
                    model = TicketRepository.GetAllTickets()
                        .ToList()
                        .Where(ticket => TicketRepository.CanUserViewTicket(userId, ticket.Id))
                        .Select(ticket =>
                        {
                            bool isWatching = TicketNotificationRepository.IsUserSubscribedToTicket(userId, ticket.Id);
                            return TicketIndexViewModel.CreateNewViewModel(userId, ticket, isWatching);
                        }).ToList();
                }
            }
            else
            {
                model = TicketRepository.GetAllTickets()
                    .ToList()
                    .Where(ticket => TicketRepository.CanUserViewTicket(userId, ticket.Id))
                    .Select(ticket =>
                    {
                        bool isWatching = TicketNotificationRepository.IsUserSubscribedToTicket(userId, ticket.Id);
                        return TicketIndexViewModel.CreateNewViewModel(userId, ticket, isWatching);
                    }).ToList();
            }

            return View(model);
        }

        // GET: Ticket/Details/{id}
        [OverrideCurrentNavLinkStyle("ticket-index")]
        public ActionResult Details(Guid? id)
        {
            if (!id.HasValue || Guid.Empty == id.Value || string.IsNullOrWhiteSpace(id.Value.ToString()))
            {
                return RedirectToAction(nameof(Index));
            }

            Ticket foundTicket = TicketRepository.GetTicket(id.Value);

            if (foundTicket == null)
            {
                return RedirectToAction(nameof(Index), new { error = "Ticket wasn't found" });
            }

            string userId = User.Identity.GetUserId();
            bool canViewTicket = TicketRepository.CanUserViewTicket(userId, foundTicket);

            if (!canViewTicket)
            {
                return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = "You cannot view this ticket (you don't have permission)" });
            }

            TicketDetailsViewModel model = TicketDetailsViewModel.CreateNewViewModel(userId, foundTicket, DbContext);

            return View(model);
        }

        // GET: Ticket/Create
        [BugTrackerAuthorize(nameof(UserRolesEnum.Submitter))]
        [OverrideCurrentNavLinkStyle("ticket-index")]
        [Route("Ticket/Create")] //! this is needed because of the route on the index (I don't know why)
        public ActionResult Create(Guid? projectId)
        {
            string userId = User.Identity.GetUserId();

            if (!UserRoleRepository.IsUserInRole(userId, UserRolesEnum.Submitter))
            {
                throw new Exception("This shouldn't happen");
            }

            if (projectId.HasValue && ProjectRepository.IsUserAssignedToProject(userId, projectId.Value))
            {
                projectId = null;
            }

            List<SelectListItem> userProjects = null;

            if (User.IsInRole(UserRolesEnum.Admin.ToString()) || User.IsInRole(UserRolesEnum.ProjectManager.ToString()))
            {
                userProjects = ProjectRepository.GetAllProjects()
                    .Select(project => new SelectListItem()
                    {
                        Text = project.Name,
                        Value = project.Id.ToString(),
                        Selected = projectId.HasValue ? project.Id == projectId.Value : false,
                    }).ToList();
            }
            else
            {
                userProjects = ProjectRepository.GetUserProjects(userId)
                    .Select(project => new SelectListItem()
                    {
                        Text = project.Name,
                        Value = project.Id.ToString(),
                        Selected = projectId.HasValue ? project.Id == projectId.Value : false,
                    }).ToList();
            }


            if (userProjects == null)
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }


            TicketCreateViewModel model = new TicketCreateViewModel()
            {
                AuthorId = userId,
                Projects = userProjects,
            };

            if (!model.Projects.Any())
            {
                return RedirectToAction(nameof(HomeController.UnauthorizedRequest), "Home", new { error = "You don't have any project to assign a ticket to.\nPLEASE CONTACT ADMIN to get assigned to a project" });
            }

            return View(model);
        }

        // POST: Ticket/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [BugTrackerAuthorize(nameof(UserRolesEnum.Submitter))]
        [Route("Ticket/Create")] //! this is needed because of the route on the index (I don't know why)
        public ActionResult Create(TicketCreateViewModel formData)
        {
            if (formData == null || !ModelState.IsValid || !formData.Type.HasValue || !formData.Priority.HasValue)
            {
                ModelState.AddModelError("", "Error - Bad data");
                formData = GenerateTicketCreateViewModelFromExisting(formData) ?? throw new Exception("bad data");

                return View(formData);
            }

            // if user is submitter and admin or project manager, then allow him/her to give a different status on ticket creation
            if (User.IsInRole(UserRolesEnum.Admin.ToString()) || User.IsInRole(UserRolesEnum.ProjectManager.ToString()))
            {
                formData.Status = formData.Status ?? TicketStatusesEnum.Open;
            }
            else
            {
                formData.Status = TicketStatusesEnum.Open;
            }

            try
            {
                Ticket newTicket = TicketRepository.CreateNewTicket(formData, (true, true));

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Error - Bad data");
                ModelState.AddModelError("", e.Message); // TODO: Remove after project completion (on staging phase)
                formData = GenerateTicketCreateViewModelFromExisting(formData) ?? throw new Exception("bad data");

                return View(formData);
            }
        }

        [NonAction]
        [OverrideCurrentNavLinkStyle("ticket-index")]
        private TicketCreateViewModel GenerateTicketCreateViewModelFromExisting(TicketCreateViewModel formData)
        {
            string userId = User.Identity.GetUserId();
            List<SelectListItem> userProjects = null;

BugTracker/Views/Shared/UnauthorizedRequest.cshtml
@{
    ViewBag.Title = "Unauthorized Request";
}

<div @*class="col-lg-4"*@>
    <div class="card">
        <div class="header">
            <h4 class="title text-danger">
                Access Denied
            </h4>
            <p class="category">
                @ViewBag.Title
            </p>
        </div>
        <div class="content">
            @* CONTENT HERE *@
            @if (!string.IsNullOrWhiteSpace(ViewBag.PermissionError))
            {
                <p class="text-warning">@ViewBag.PermissionError</p>
            }
            
            @if (!string.IsNullOrWhiteSpace(ViewBag.Error))
            {
                <p class="text-warning">@ViewBag.Error</p>
            }

            @* FOOTER HERE *@
            <div class="footer">
                <div class="legend">
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                </div>
                <hr />
                <div class="stats">
                    <i class="pe-7s-key" style="font-weight: 600; font-size: 125%; position: relative; top: 3px;"></i> @Html.ActionLink("Go To Login Page", nameof(AccountController.Login), "Account")
                </div>
            </div>
        </div>
    </div>
</div>

BugTracker/Views/Shared/_Layout.cshtml
@{
    string overrideCurrentPage = ViewBag.OverrideCurrentPage;
    //string currentController = ViewContext.RouteData.Values["controller"] as string ?? "Home";
    //string currentAction = ViewContext.RouteData.Values["action"] as string ?? "Index";
    //string currentPage = string.IsNullOrWhiteSpace(overrideCurrentPage) ?
    //    (currentController + "-" + currentAction).ToLower() :
    //    overrideCurrentPage;
    string currentPage = overrideCurrentPage;
    bool guestMode = !User.Identity.IsAuthenticated;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render(@"~/fonts-google")
    @Styles.Render(@"~/font-awesome")
    @Styles.Render(@"~/Content/css")
    @Styles.Render(@"~/Template/css")
    @RenderSection("Styles", false)
    @Styles.Render(@"~/MyContent/css")
    @Scripts.Render(@"~/bundles/modernizr")
</head>
<body>
    <span id="currentPage" data-page="@currentPage" class="text-hide"></span>


    <div class="wrapper">
        <div class="sidebar" data-color="@(guestMode ? "" : "blue")" data-image="@Url.Content("~/Template/assets/img/sidebar-5.jpg")">
            <!--

                Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple
                Tip 2: you can also add an image using data-image tag

            -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a href="@Url.Action(nameof(HomeController.Index), "Home")" class="simple-text">
                            Bug Tracker
                        </a>
                    }
                    else
                    {
                        <span class="simple-text" style="cursor: default; user-select: none;">Bug Tracker</span>
                    }
                </div>
                <ul class="nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li id="home-index" class="my-page-link">
                            <a href="@Url.Action(nameof(HomeController.Index), "Home")">
                                <i class="pe-7s-graph"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                    }

                    @if (User.IsInRole(nameof(UserRolesEnum.Admin)))
                    {
                        <!--TODO: Update the li's "id" to match "controller-action"-->
                        <li class="my-page-link" id="userrole-index">
                            @*<a href="./Template/notifications.html">*@
                            <a href="@Url.Action(nameof(UserRoleController.Index), new { controller = "UserRole" })">
                                <i class="pe-7s-edit"></i>
                                <p>Manage Users</p>
                            </a>
                        </li>
                    }

                    @if (User.IsInRole(nameof(UserRolesEnum.Admin)) || User.IsInRole(nameof(BugTracker.MyHelpers.UserRolesEnum.ProjectManager)))
                    {
                        <li class="my-page-link" id="project-all">
                            @*<a href="./Template/table.html">*@
                            <a href="@Url.Action(nameof(ProjectController.All), "Project")">
                                <i class="pe-7s-safe"></i>
                                <p>All Projects</p>
                            </a>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="my-page-link" id="project-index">
                            @*<a href="./Template/icons.html">*@
                            <a href="@Url.Action(nameof(ProjectController.Index), "Project")">
                                <i class="pe-7s-box1"></i>
                                <p>My Projects</p>
                            </a>
                        </li>


                        <li class="my-page-link" id="ticket-index">
                            @*<a href="./Template/icons.html">*@
                            <a href="@Url.Action(nameof(TicketController.Index), "Ticket", new { whatTickets = "" })">
                                <i class="pe-7s-ticket"></i>
                                <p>All Tickets</p>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="@(Url.Action((ViewContext.RouteData.Values["action"] as string) ?? "Index", (ViewContext.RouteData.Values["controller"] as string) ?? "Home"))">
                            @ViewBag.Title
                        </a>

                    </div>

                    <div class="collapse navbar-collapse">
                        <!--
                        <ul class="nav navbar-nav navbar-left">
                            <li>
                                @*Update Link*@
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-dashboard"></i>
                                </a>
                            </li>
                        </ul>
                        -->
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </nav>


            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>


            <footer class="footer">
                @*<div class="container-fluid">*@
                <div>
                    <nav class="pull-left">
                        <ul>
                            <li>
                                @*Update Link*@
                                <a href="@Url.Action(nameof(HomeController.Index), "Home")">
                                    Home
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy; @DateTime.Now.Year <a href="@Url.Action(nameof(HomeController.Index), "Home")">Bug Tracker</a>, made for a better project management
                    </p>
                </div>
            </footer>
        </div>
    </div>


    @Scripts.Render(@"~/bundles/jquery")
    @Scripts.Render(@"~/bundles/bootstrap")
    @Scripts.Render(@"~/Template/js")
    @Scripts.Render(@"~/MyContent/js")
    @RenderSection("scripts", required: false)
</body>
</html>